### ISSUE TITLE
Hello buddy

### ISSUE THREAD

**Issue by anes66** [Musiker15/msk_backpack#1]
ou hello buddy again with nice stuff here nice to see somthing new :slight_smile: 

is it possible to make when you equip the baackpack that you can carry more stuff (weight) like normal you can carry without backpaack 35kg and with backpack 50kg and to make more backpacks with different weight

**Comment by Musiker15** [comment]
Yes it is possible. I can have a look at this feature and implement in the next Update if you want :)

**Comment by Musiker15** [comment]
I didn't test it but you can try to add the following in `esx_backpack` :)

`config.lua`
```lua
Config.BagInventory = false -- Set true if you don't want the pocket inventory but want to expand the player inventory
Config.BagWeight = 50 -- Set the Bag Weight if 'Config.BagInventory = true'
```
Then replace in `server.lua`
```lua
-- Bag
ESX.RegisterUsableItem('bag', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
    local hasBag = xPlayer.getInventoryItem('nobag')
    
    if hasBag.count == 0 then
        TriggerClientEvent('esx_bag:setBag', source)
        xPlayer.removeInventoryItem('bag', 1)
        xPlayer.addInventoryItem("nobag", 1)
        if Config.BagInventory then
            xPlayer.setMaxWeight(ESX.GetConfig().MaxWeight + Config.BagWeight)
        end
        TriggerClientEvent('esx:showNotification', source, _U('used_bag'))
    else
        TriggerClientEvent('esx:showNotification', source, _U('has_bag'))
    end
end)

-- No Bag
ESX.RegisterUsableItem('nobag', function(source)
	local xPlayer = ESX.GetPlayerFromId(source)
    local hasBag = xPlayer.getInventoryItem('bag')

    if hasBag.count == 0 then
        TriggerClientEvent('esx_bag:setdelBag', source)
        xPlayer.removeInventoryItem('nobag', 1)
        xPlayer.addInventoryItem("bag", 1)
        if Config.BagInventory then
            xPlayer.setMaxWeight(ESX.GetConfig().MaxWeight)
        end
        TriggerClientEvent('esx:showNotification', source, _U('used_nobag'))
    else
        TriggerClientEvent('esx:showNotification', source, _U('had_bag'))
    end
end)
```

**Comment by anes66** [comment]
Will test it out but 1 question it would be great when we can put more bag models with different weight. I have like nike puma bags and different types with different weight

**Comment by anes66** [comment]
> I didn't test it but you can try to add the following in `esx_backpack` :)
> 
> `config.lua`
> 
> ```lua
> Config.BagInventory = false -- Set true if you don't want the pocket inventory but want to expand the player inventory
> Config.BagWeight = 50 -- Set the Bag Weight if 'Config.BagInventory = true'
> ```
> 
> Then replace in `server.lua`
> 
> ```lua
> -- Bag
> ESX.RegisterUsableItem('bag', function(source)
> 	local xPlayer = ESX.GetPlayerFromId(source)
>     local hasBag = xPlayer.getInventoryItem('nobag')
>     
>     if hasBag.count == 0 then
>         TriggerClientEvent('esx_bag:setBag', source)
>         xPlayer.removeInventoryItem('bag', 1)
>         xPlayer.addInventoryItem("nobag", 1)
>         if Config.BagInventory then
>             xPlayer.setMaxWeight(ESX.GetConfig().MaxWeight + Config.BagWeight)
>         end
>         TriggerClientEvent('esx:showNotification', source, _U('used_bag'))
>     else
>         TriggerClientEvent('esx:showNotification', source, _U('has_bag'))
>     end
> end)
> 
> -- No Bag
> ESX.RegisterUsableItem('nobag', function(source)
> 	local xPlayer = ESX.GetPlayerFromId(source)
>     local hasBag = xPlayer.getInventoryItem('bag')
> 
>     if hasBag.count == 0 then
>         TriggerClientEvent('esx_bag:setdelBag', source)
>         xPlayer.removeInventoryItem('nobag', 1)
>         xPlayer.addInventoryItem("bag", 1)
>         if Config.BagInventory then
>             xPlayer.setMaxWeight(ESX.GetConfig().MaxWeight)
>         end
>         TriggerClientEvent('esx:showNotification', source, _U('used_nobag'))
>     else
>         TriggerClientEvent('esx:showNotification', source, _U('had_bag'))
>     end
> end)
> ```

1 more question can you make that we have 3-4 types of bag and to choice with different texture the bag if you know what i mean there are bags like police fib and other like addidas nike

i hope you understand what i mean

**Comment by Musiker15** [comment]
No, sorry. It's possible but I don't have that much time.

**Comment by anes66** [comment]
> No, sorry. It's possible but I don't have that much time.

ok no problem if i have permission i would do it when im done i will make a request
