### ISSUE TITLE
ox inventory

### ISSUE THREAD

**Issue by DARKAOFF** [Musiker15/msk_backpack#11]
hello, does the bag work with ox_inventory? because I did not succeed thank you

**Comment by Musiker15** [comment]
As you can read in the Readme.md you only need the Chezza Inventory with `Config.BagInventory = 'secondary'`
With `Config.BagInventory = 'expand'` you can you every Inventory but Chezza Inventory is still recommended.

**Comment by DARKAOFF** [comment]
yes yes that's what i did but it doesn't work ^^

**Comment by Musiker15** [comment]
My cars engine doesnt start. You know what the problem is? -.-

I cant help if you dont tell me what exactly doesnt work.

**Comment by DARKAOFF** [comment]
sorry lol sorry. I configured it correctly but in game nothing happens when I click on use item. And the inventory does not increase. I don't have any client or server errors either.

**Comment by Musiker15** [comment]
So f.e. default is 60 weight and with backpack it will add 30 but you still have 60 after using the item?

Do you see this print in your server console if you set Config.Debug = true ? (setPlayerBag: NUMBER)

Try to change this in server.lua
```lua
function setPlayerBag(xPlayer, weight)
    if xPlayer then
        debug('setPlayerBag:', weight)
        xPlayer.setMaxWeight(weight)
    end
end
```

**Comment by Musiker15** [comment]
If that doesn't work I cant help you. Use the integrated system from oxinventory
