### ISSUE TITLE
Skin Issue with expand inventory

### ISSUE THREAD

**Issue by Leo28021989** [Musiker15/msk_backpack#7]
Es gibt ein Problem mit der Tasche und dem Cheeza V4 man bekommt wenn man die Tasche angelegt hat und diese wieder ablegen möchte , kommt immer die Meldung so lange sich items in der Tasche befinden kann man sie nicht ablegen . Aber ich habe keine Items in der Tasche

**Comment by Musiker15** [comment]
Ah Mist da hab ich die Dev Version von mir aus versehen hochgeladen...

**Comment by Musiker15** [comment]
Mach `Config.ItemsInBag = false`

**Comment by Musiker15** [comment]
Steht aber dabei, dass man das auf false lassen soll

**Comment by Leo28021989** [comment]
Okay mache ich wird das den noch gefixxt von dir ?

**Comment by Leo28021989** [comment]
axo sorry habs übersehen

**Comment by Musiker15** [comment]
-- Experimental // Not working at the moment!

**Comment by Leo28021989** [comment]
Oh sorry

**Comment by Musiker15** [comment]
Ich versuche es und ich hoffe das klappt demnächst. Mit SQL hab ich noch so meine Probleme leider...

**Comment by Leo28021989** [comment]
Okay kein problem aber in der config habe ich gerade geschaut da steht das nicht das es nicht mit Cheeza funktioniert ^^

**Comment by Musiker15** [comment]
Das Problem wurde mit der neusten Version behoben :)

**Comment by Leo28021989** [comment]
Aber es gibt ein Problem wenn ich das Inventar erweiter und mich aus und wieder einlogge bzw verbinde auf den Server wird mein Char auf den Standart Charakter zurückgesetzt . Ebenso kommt die Meldung beim Verbinden Tasche wurde aus dem Inventar entfernt und dann wieder hinzugefügt

**Comment by Musiker15** [comment]
**Was meinst du mit Standard Charakter zurück gesetzt?**
Nach einem Relog wird die Tasche vom Spieler entfernt, da ich bisher keine Lösung gefunden habe das Inventar nach Relog weiterhin automatisch zu erweitern. 

Die Meldung kommt aus dem gerade genannten Grund. Deshalb muss die Tasche einfach wieder erneut benutzt werden damit das Inventar erweitert wird.

Das ist kein bug sondern vorerst so gewollt bis ich eine Lösung dafür gefunden habe.

**Comment by Leo28021989** [comment]
Ja um deutlicher auszudrücken wenn ich das erweiterte Inventar nutze und mich dann auslogge und wieder einlogge bin ich nen Kajo

**Comment by Musiker15** [comment]
Benutzt du `esx_skin` und `skinchanger`? Wenn ja verstehe ich das Problem nicht.
Wenn du `brp-fivem-appearance` nutzt dann liegt es definitiv daran denn damit ist mein Script nicht kompatibel!

**Comment by Leo28021989** [comment]
nutze ganz normal esx legacy also mit esx_skin und dem skinchanger

**Comment by Musiker15** [comment]
Dann kann das eigentlich nicht sein. Es wird nur der Skin der Tasche entfernt und ansonsten nichts geändert.

**Comment by Leo28021989** [comment]
Die Tasche wird mir ja kurz aus dem Inventar entfernt und bekomme sie dann wieder beim einloggen

**Comment by Musiker15** [comment]
Genau. Das Item `nobag` wird entfernt und das Item `bag` bekommt man nach einem Relog.
Zusätzlich wird der Skin der Tasche auf 0 gesetzt, also vom PED entfernt. 
Mehr passiert nicht.

**Comment by Leo28021989** [comment]
Ok ich probiere es jetzt nochmal eben

**Comment by Musiker15** [comment]
Hoffentlich nutzt du auch die neuste Version v2.4 und hast das Plugin ebenfalls ausgetauscht und die entsprechenden Dinge in die config.lua vom Chezza Inventory eingetragen die in der Readme.md stehen.

**Comment by Musiker15** [comment]
https://github.com/Musiker15/esx_backpack/releases/tag/v2.4

**Comment by Leo28021989** [comment]
Hab ich alles gemacht bin jetzt connect und direkt wieder nen kajo

**Comment by Musiker15** [comment]
Nutzt du sicher nicht noch irgendwas anderes was Kleidung bzw den Skin angeht?

**Comment by Leo28021989** [comment]
Nein nutze ich nicht

**Comment by Musiker15** [comment]
Dann bin ich tatsächlich komplett überfragt. Eventuell liegt das tatsächlich an ESX Legacy...
Ich nutze nämlich esx 1.2 (v1final)

**Comment by Leo28021989** [comment]
Aber in der client Zeile 12 local xPlayer = ESX.IsPlayerLoaded(playerPed) ist das so richtig , weil IsPlayerLoaded kenn ich jetzt so nicht

**Comment by Musiker15** [comment]
Ja das ist korrekt. Das gibt nur aus ob der Spieler geladen ist oder nicht und wenn ja dann führe etwas aus.

**Comment by Leo28021989** [comment]
Okay ja dann ist das wohl mit Legacy nicht kompatibel

**Comment by Musiker15** [comment]
Eventuell kann ich den clientseitigen Code den du gerade genannt hast auf die Serverseitge packen dann klappt das eventuell dass ich nach dem Relog direkt wieder das Inventar erweitern kann. 
Ich werde das die nächsten Tage testen und dann gibt es eventuell ein Update wenn ich das hinbekomme :)

**Comment by Leo28021989** [comment]
Okay alles klar weiß ich bescheid danke dir :)
